### ISSUE TITLE
Error when loading local file from RPM install

### ISSUE THREAD

**Issue by jw3** [ctc-oss/fapolicy-analyzer#179]
```
$ fapolicy-analyzer 
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Traceback (most recent call last):
  File "/usr/lib64/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib64/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/lib/python3.9/site-packages/fapolicy_analyzer/ui/__main__.py", line 5, in <module>
    from .main_window import MainWindow
  File "/usr/lib/python3.9/site-packages/fapolicy_analyzer/ui/main_window.py", line 5, in <module>
    from .ui_widget import UIWidget
  File "/usr/lib/python3.9/site-packages/fapolicy_analyzer/ui/ui_widget.py", line 12, in <module>
    with resources.path("fapolicy_analyzer", "locale") as path:
  File "/usr/lib64/python3.9/contextlib.py", line 117, in __enter__
    return next(self.gen)
  File "/usr/lib64/python3.9/importlib/resources.py", line 175, in _path_from_reader
    opener_reader = reader.open_resource(norm_resource)
  File "<frozen importlib._bootstrap_external>", line 995, in open_resource
IsADirectoryError: [Errno 21] Is a directory: '/usr/lib/python3.9/site-packages/fapolicy_analyzer/locale'
```

https://github.com/ctc-oss/fapolicy-analyzer/releases/download/v0.2.0-rc3/fapolicy-analyzer-0.2.0-0.rc3.fc34.x86_64.rpm

The RPM contains

`/usr/lib/python3.9/site-packages/fapolicy_analyzer/locale/es/LC_MESSAGES/fapolicy_analyzer.mo`

**Comment by tparchambault** [comment]
For the FC32 rpm, 
![FC32_PyStack](https://user-images.githubusercontent.com/36828847/128209801-4bf3e0a0-806e-4c80-b144-1cb4288884bf.png)

**Comment by jw3** [comment]
fixed in #180
