### ISSUE TITLE
Python3 "gi" module requirement not being installed by yum/dnf on RHEL8

### ISSUE THREAD

**Issue by scholarsmate** [ctc-oss/fapolicy-analyzer#348]
```shell
[root@rhel8 vagrant]# yum install ./fapolicy-analyzer-0.0.0-1.182.gf69f80c.el8.x86_64.rpm
Updating Subscription Management repositories.
Last metadata expiration check: 1:35:08 ago on Fri 17 Dec 2021 05:56:00 PM UTC.
Dependencies resolved.
=======================================================================================================================================================================
 Package                                   Architecture                   Version                                           Repository                            Size
=======================================================================================================================================================================
Installing:
 fapolicy-analyzer                         x86_64                         0.0.0-1.182.gf69f80c.el8                          @commandline                         710 k

Transaction Summary
=======================================================================================================================================================================
Install  1 Package

Total size: 710 k
Installed size: 2.3 M
Is this ok [y/N]: y
Downloading Packages:
Running transaction check
Transaction check succeeded.
Running transaction test
Transaction test succeeded.
Running transaction
  Preparing        :                                                                                                                                               1/1
  Installing       : fapolicy-analyzer-0.0.0-1.182.gf69f80c.el8.x86_64                                                                                             1/1
  Running scriptlet: fapolicy-analyzer-0.0.0-1.182.gf69f80c.el8.x86_64                                                                                             1/1
  Verifying        : fapolicy-analyzer-0.0.0-1.182.gf69f80c.el8.x86_64                                                                                             1/1
Installed products updated.

Installed:
  fapolicy-analyzer-0.0.0-1.182.gf69f80c.el8.x86_64

Complete!
[root@rhel8 vagrant]# fapolicy-analyzer
Traceback (most recent call last):
  File "/usr/lib64/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib64/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/lib/python3.9/site-packages/fapolicy_analyzer/ui/__main__.py", line 21, in <module>
    import gi
ModuleNotFoundError: No module named 'gi'
[root@rhel8 vagrant]#
```

On Fedora however, it does pull in dependencies:

```shell
[root@fedora vagrant]# yum install ./fapolicy-analyzer-0.0.0-1.182.gf69f80c.fc34.x86_64.rpm
Last metadata expiration check: 0:16:45 ago on Fri 17 Dec 2021 07:09:08 PM UTC.
Dependencies resolved.
==============================================================================================================================================================================================================================================
 Package                                                        Architecture                                   Version                                                             Repository                                            Size
==============================================================================================================================================================================================================================================
Installing:
 fapolicy-analyzer                                              x86_64                                         0.0.0-1.182.gf69f80c.fc34                                           @commandline                                         926 k
Installing dependencies:
 python3-gobject-base                                           x86_64                                         3.40.1-1.fc34                                                       fedora                                               320 k
Installing weak dependencies:
 python3-configargparse                                         noarch                                         1.3-1.fc34                                                          fedora                                                38 k
 python3-events                                                 noarch                                         0.3-11.fc34                                                         fedora                                                19 k
 python3-gobject                                                x86_64                                         3.40.1-1.fc34                                                       fedora                                                17 k
 python3-more-itertools                                         noarch                                         8.5.0-2.fc34                                                        fedora                                                65 k
 python3-rx                                                     noarch                                         3.1.1-3.fc34                                                        fedora                                               288 k

Transaction Summary
==============================================================================================================================================================================================================================================
Install  7 Packages
...
```

**Comment by tparchambault** [comment]
Independent of Vagrant, we have two issues to address with RHEL8:

1. The RHEL8 default python version is 3.6, so our wrapper script which specifies python3 will invoke python3.6 if it exists on the system. - We can address this by hard-coding the python version number in the wrapper, i.e. `python3.9`.
2. I don't believe there are python-gobject rpms current available from the RHEL8 repos for 3.9 (at least one that provides gi). We can possibly address this by installing via pip as superuser. It will install the PyGobject modules under `/usr/local/lib[64?]/`. @jw3, I'm curious what your thoughts are on this approach. Not sure it's feasible in a post-inst script in the spec file.

Fwiw, RHEL9 is in beta testing now. Its default python version is 3.9.

**Comment by tparchambault** [comment]
Verified that `git` is provided in Py3.6 on RHEL8 by the python3-gobject-base pkg. Py3.9 does not have a similarly named rpm in the default RHEL8 repos. Researching the possibility of alternative rpm repos.

**Comment by tparchambault** [comment]
Not in EPEL.

**Comment by tparchambault** [comment]
As per discussion #414, between the Py rollback to 3.6, and @jw3 's work to get the dependencies into epel, we are good to go over Rhel8.
