### ISSUE TITLE
Backport to RHEL8 Py3.6 exposes missing dataclasses package. 

### ISSUE THREAD

**Issue by tparchambault** [ctc-oss/fapolicy-analyzer#498]
```
$ fapolicy-analyzer -v
pkttyagent registering on the dbus...
==== AUTHENTICATING FOR org.freedesktop.policykit.exec ====
Authentication is needed to run `/usr/bin/env' as the super user
Authenticating as:************* (****)
Password: 
==== AUTHENTICATION COMPLETE ====
Traceback (most recent call last):
  File "/usr/lib64/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib64/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/lib/python3.6/site-packages/fapolicy_analyzer/ui/__main__.py", line 26, in <module>
    from .splash_screen import SplashScreen
  File "/usr/lib/python3.6/site-packages/fapolicy_analyzer/ui/splash_screen.py", line 22, in <module>
    from .main_window import MainWindow
  File "/usr/lib/python3.6/site-packages/fapolicy_analyzer/ui/main_window.py", line 26, in <module>
    from fapolicy_analyzer.ui.ui_page import UIAction, UIPage
  File "/usr/lib/python3.6/site-packages/fapolicy_analyzer/ui/ui_page.py", line 17, in <module>
    from dataclasses import dataclass, field
ModuleNotFoundError: No module named 'dataclasses'
Terminating pkttyagent.
$
```

**Comment by dorschs57** [comment]
Looks like there is a backported lib to support dataclasses in pthon 3.6 https://pypi.org/project/dataclasses/. There is also an RPM available for the lib in EPEL.
