### ISSUE TITLE
Fix Gtk version in fapolicyd config file editor UI elements

### ISSUE THREAD

**Issue by tparchambault** [ctc-oss/fapolicy-analyzer#923]
We are using an older Gtk minimum version to support RHEL 8.

**Comment by jw3** [comment]
See discussion https://github.com/ctc-oss/fapolicy-analyzer/discussions/916#discussioncomment-7265806

```


DEBUG:root:_PostInitCaller.__call__((), {})
Traceback (most recent call last):
  File "/usr/lib64/python3.6/site-packages/fapolicy_analyzer/ui/main_window.py", line 454, in on_configAdminMenu_activate
    self.__pack_main_content(router(PAGE_SELECTION.CONFIG))
  File "/usr/lib64/python3.6/site-packages/fapolicy_analyzer/ui/main_window.py", line 78, in router
    return route(*data)
  File "/usr/lib64/python3.6/site-packages/fapolicy_analyzer/ui/ui_widget.py", line 40, in __call__
    obj = type.__call__(cls, *args, **kwargs)
  File "/usr/lib64/python3.6/site-packages/fapolicy_analyzer/ui/config_admin_page.py", line 50, in __init__
    UIConnectedWidget.__init__(self, features=features)
  File "/usr/lib64/python3.6/site-packages/fapolicy_analyzer/ui/ui_widget.py", line 122, in __init__
    UIBuilderWidget.__init__(self)
  File "/usr/lib64/python3.6/site-packages/fapolicy_analyzer/ui/ui_widget.py", line 93, in __init__
    self._builder.add_from_string(glade)
  File "/usr/lib64/python3.6/site-packages/gi/overrides/Gtk.py", line 465, in add_from_string
    return Gtk.Builder.add_from_string(self, buffer, length)
GLib.Error: gtk-builder-error-quark: .:21:1 Required gtk+ version 3.24, current version is 3.22 (7)
```
