### ISSUE TITLE
Transition away from profiler fails on unsaved changes check

### ISSUE THREAD

**Issue by jw3** [ctc-oss/fapolicy-analyzer#940]
The logic looking at unsaved changes causes failure when navigating away from the profiler page.

1. Navigate to the profiler
2. Navigate away from the profiler
3. Observe stack trace

```
Traceback (most recent call last):
  File "/usr/lib64/python3.11/site-packages/fapolicy_analyzer/ui/main_window.py", line 479, in on_configAdminMenu_activate
    self.__pack_main_content(router(PAGE_SELECTION.CONFIG))
  File "/usr/lib64/python3.11/site-packages/fapolicy_analyzer/ui/main_window.py", line 180, in __pack_main_content
    if hasattr(self.__page, "_unsaved_changes") and self.__page._unsaved_changes:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/events/events.py", line 93, in __getattr__
    raise EventsException("Event '%s' is not declared" % name)
events.events.EventsException: Event '_unsaved_changes' is not declared
```

[**main_window.py", line 180**](https://github.com/ctc-oss/fapolicy-analyzer/blob/master/fapolicy_analyzer/ui/main_window.py#L180)
 
ht: https://github.com/ctc-oss/fapolicy-analyzer/discussions/916#discussioncomment-7442237

#921

**Comment by jw3** [comment]
This issue was weird because it only failed on some UI pages. Looking at the events code

events.py 91
```
        if hasattr(self, '__events__'):
            if name not in self.__events__:
                raise EventsException("Event '%s' is not declared" % name)
```

So if the page had declared an `__events__` list, the thing has to be in it, otherwise its happy to just introspect the properties of the object.
